development:
  adapter: sqlite3
  database: db/website_development.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: website_production
  pool: 5
  username: postgres
  password: